services:
  collabreef-collab:
    build:
      context: .
      dockerfile: Dockerfile
    image: collabreef/collabreef:local
    container_name: collabreef-collab
    command: ["node", "collab/src/index.js"]
    volumes:
      - "./bin:/usr/local/app/bin"
    environment:
      - PORT=3000
      - DB_DRIVER=sqlite3
      - DB_DSN=/usr/local/app/bin/collabreef.db
    restart: unless-stopped

  collabreef-web:
    image: collabreef/collabreef:local
    container_name: collabreef-web
    command: ["./web"]
    ports:
      - "8080:8080"
    volumes:
      - "./bin:/usr/local/app/bin"
    environment:
      - PORT=8080
      - DB_DRIVER=sqlite3
      - DB_DSN=/usr/local/app/bin/collabreef.db
      - APP_DISABLE_SIGNUP=${APP_DISABLE_SIGNUP}
      - APP_SECRET=${APP_SECRET}
      - COLLAB_URL=http://collabreef-collab:3000
    depends_on:
      collabreef-collab:
        condition: service_started
    restart: unless-stopped
